paper_date: 2023-07-03 # date of paper 1st circulation to select departed or newly joined ST/board/associate/EO members
authors:
  lead_author: Andrea Fortier
  # up to 4 major contributors:
  major_contributors_list: ['Attila Simon', 'Christopher Broeg', 'Göran Olofsson', 'Adrien Deline']
  # exactly 4 Science Enablers - rotating from the full list of SE:
  science_enablers_list: ['Thomas Wilson', 'Pierre Maxted', 'Alexis Brandeker', 'Andrew Collier Cameron'] 
  # significant contributors (max 15%):
  significant_contributors_list: ['Mathias Beck', 'Anja Bekkelien', 'Nicolas Billot', 'Andrea Bonfanti', 'Giovanni Bruno', 'Laetitia Delrez', 'Brice-Olivier Demory', 
                               'David Futyan','Hans-Gustav Florén', 'Maximilian Günther', 'Alexis Heitzmann', 'Sergio Hoyer', 'Kate G. Isaak', 'Sérgio Sousa', 
                               'Manu Stalport', 'Arnaud Turin', 'Peter Verhoeve'  ]
  # Remaining authors to add to alphabetical list (all that are not automatically added such as CST, Associate, Board, EO, MA, ESAPS):                          
  selected_list: ['Gisbert Peter', 'Roland Ottensamer', 'Demetrio Magrin', 'Matteo Munari', 'Amador Lopez Pina', 'David Modrego', 'Pascal Guterman', 'test man','Tiziano Zingales'] 
  # 5 People nominated by the MAs:
  MA_nominees: ['Federico Biondi', 'Francesco Ratti', 'Francesco Verrecchia', 'Maximilian Buder', 'Bernd Ulmer']
filenames:
  Source_of_author_data: Notion and CSV # Notion or CSV or 'Notion and CSV'
  filename_CSV: additional_authors.csv # the filename to read the CSV for CSV option
flags:
  affil: \inst            # or one of the following examples:  affil = '\affil';   affil = '$^';  \inst
  author_separator: ', '  # separator used between authors: ', ' or '\and '  (do not use "")
  flag_initials: true     # set to False if you want to print full Names, not initials
  flag_orcid: true        # set to False if you don't want the link to orcid ID in the author list
  flag_inst_label: True   # how to enumerate the institutes: True: uses \label{inst:nn}, False uses $^{nn}$
